#!/bin/bash
. uploadMP3s.prop
album="${PWD##*/}"
checkMp3s "$album"
if [ "$?" = "0" ];then
ftp -i -n -v <<-EOF
open ftp.stylishcarpet.com
user $user $password
mkdir "$album"
cd "$album"
mput *
bye
EOF
  echo uploaded: `date` > uploaded
else
  echo THIS ALBUM ALREADY EXISTS ON THE FTP SERVER SO I AM NOT UPLOADING IT
  echo "`date`: $album already exists" >> tmp.album.exists
fi
